# Chapter 2
## Matrices and Gaussian Elimination
선형 연립방정식을 푼다는 것은 각각의 일차방정식을 동시에 만족하는 변수들의 값을 정하는 것이다. 이 풀이 과정을 체계화 한것이 Gaussian Elimination으로 두번째 일차식에서 변수 한개를 소거하고 세번째 일차식에서는 두번째 식에서 소거된 변수 외에 또 다른 변수까지 두 변수를 소거하는 방식으로 진행하여 마지막 식에서는 변수가 한 개만 남도록 만든다. 그러면 마지막식에서 포함된 변수의 값을 읽어낼 수 있고, 직전 식에 해당 변수값을 대입하면 또 다른 변수의 값이 정해지는 방식으로 모든 변수의 값을 정할 수 있다.

## 2.1 Matrix Operations
행렬과 벡터의 곱에서 행렬간의 곱셈으로 확장한다면, 크기가 $n \times l$ 인 $A = [b_1|b_2|...|b_l] = (b_{jk})$ 가 주어졌다고 하면, 
$k$ 번째 열 $b_k$ 와 $A$의 곱은 $Ab_k = b_{1k}a_1 + b_{2k}a_2 + ... + b_{nk}a_n$ 이다.


두 행별의 $A$와 $B$의 곱 $AB$는 다음과 같이 정의된다:


$$AB = [Ab_1|Ab_2|...|Ab_l]$$


여기서 각 열 $Ab_k$는 다음과 같이 계산된다:


$$Ab_k = A \cdot b_k = b_{1k}a_1 + b_{2k}a_2 + ... + b_{nk}a_n$$


첫번째 행렬과 두번째 행렬의 열이 곱해지므로 첫번째 행렬의 열의 개수와 두번째 행렬의 행의 개수가 일치해야한다

행렬간의 곱은 결합법칙 $(AB)C = A(BC)$가 성립하고, 행렬간의 덧셈과 곱셈은 분배법칙 $A(B+C) = AB+AC$, $(B+C)D = BD+CD$가 성립한다.


In [ ]:
import numpy as np

# 행렬 정의
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

C = np.array([[9, 10],
              [11, 12]])

# 결합법칙 (AB)C = A(BC)
print("AB:")
print(np.dot(A, B))
AB = np.dot(A, B)

print("\nABC:")
ABC = np.dot(AB, C)
for i in range(ABC.shape[0]):
    for j in range(ABC.shape[1]):
        print(f"ABC[{i},{j}] =", end=" ")
        for k in range(B.shape[0]):
            print(f"({AB[i,k]}*{C[k,j]})", end=" + " if k < B.shape[0] - 1 else "",)
        print(f"= {ABC[i,j]}")

print("\nA(BC):")
BC = np.dot(B, C)
ABC = np.dot(A, BC)
for i in range(ABC.shape[0]):
    for j in range(ABC.shape[1]):
        print(f"A(BC)[{i},{j}] =", end=" ")
        for k in range(BC.shape[0]):
            print(f"({A[i,k]}*{BC[k,j]})", end=" + " if k < BC.shape[0] - 1 else "",)
        print(f"= {ABC[i,j]}")

# 분배법칙 A(B+C) = AB+AC
print("\n(B+C):")
BC = B + C
print(BC)

print("\nA(B+C):")
ABC = np.dot(A, BC)
for i in range(ABC.shape[0]):
    for j in range(ABC.shape[1]):
        print(f"A(B+C)[{i},{j}] =", end=" ")
        for k in range(BC.shape[0]):
            print(f"({A[i,k]}*{BC[k,j]})", end=" + " if k < BC.shape[0] - 1 else "",)
        print(f"= {ABC[i,j]}")

print("\nAB + AC:")
AB = np.dot(A, B)
AC = np.dot(A, C)
print(AB + AC)


그러나 행렬간의 곱셈은 실수의 곱셈과 다르게 교환법칙이 성립하지 않는다. 

In [ ]:
import numpy as np

# 행렬 정의
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# AB 계산
AB = np.dot(A, B)
print("AB:")
print(AB)

# BA 계산
BA = np.dot(B, A)
print("\nBA:")
print(BA)

# AB와 BA 비교
print("\nAB == BA:", np.array_equal(AB, BA))

# 각 단계에서의 연산 과정 출력
print("\nAB:")
for i in range(AB.shape[0]):
    for j in range(AB.shape[1]):
        print(f"AB[{i},{j}] =", end=" ")
        for k in range(B.shape[0]):
            print(f"({A[i,k]}*{B[k,j]})", end=" + " if k < B.shape[0] - 1 else "",)
        print(f"= {AB[i,j]}")

print("\nBA:")
for i in range(BA.shape[0]):
    for j in range(BA.shape[1]):
        print(f"BA[{i},{j}] =", end=" ")
        for k in range(A.shape[0]):
            print(f"({B[i,k]}*{A[k,j]})", end=" + " if k < A.shape[0] - 1 else "",)
        print(f"= {BA[i,j]}")


행렬 덧셈의 항등원은 모든 원소가 0인 영행렬이고(matrix of zeros) 이며, 0으로 표시합니다. 다양한 크기의 영행렬은 0으로 표시하지만 대부분의 경우에 혼동되지 않습니다. 영행렬의 크기를 특별히 표시할 필요가 있는 경우에는 $m \times n$ 영행렬을 $0_{m,n}$으로 표시하기도 합니다.

행렬 곱셈의 항등원은 행번호와 열번호가 같은 대각원소들이 1이고, 나머지 비대각원소들은 0인 정사각행렬로서 항등행렬(identity matrix)이라고 부릅니다.


$$I = I_n = \begin{bmatrix}
1 & 0 & \cdots & 0 \\
0 & 1 & \cdots & 0 \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 & \cdots & 1 \\
\end{bmatrix}$$


대각행렬은 비대각원소가 모두 0인 행렬로, 대각원소들이 주 대각선 상에 위치합니다. 대각행렬을 $D$라고 표현하고, 만약 $i$번째 대각원소가 $d_i$이라면, 대각행렬 $D$는 다음과 같이 표현됩니다:

$$D = \begin{bmatrix} d_1 & 0 & \cdots & 0 \\ 0 & d_2 & \cdots & 0 \\ \vdots & \vdots & \ddots & \vdots \\ 0 & 0 & \cdots & d_n \\ \end{bmatrix} = diag(d_i) = diag(d_1,...,d_n)$$

여기서 $ n $은 행렬의 차원을 나타내며, $ d_i $는 $ D $의 $ i $번째 대각원소입니다.


대각행렬은 다른 행렬의 왼쪽 또는 오른쪽에 곱해지면서 scaling이라 부르는 행 또는 열에 대한 상수배 작용을 합니다. 즉, 어떤 행렬 $A$에 대해서 $AD$는 $A$의 $j$번째 열 벡터에 $d_j$를 상수배 한 것이며, $AD$는 $A$의 각 열을 $d_j$로 scaling한 행렬이 됩니다. 마찬가지로 $DA$는 $i$번째 행을 $d_i$값으로 scaling한 행렬이 됩니다.


행렬을 다룰때 행렬의 변형 한가지가 행렬의 전치(transpose)다.

주어진 예제에서 행렬 $A$는 다음과 같습니다:

$$
A = \begin{bmatrix} 2 & 1 & 4 \\ 0 & 0 & 3 \end{bmatrix}
$$

이 행렬의 전치는 행과 열을 바꾸는 것입니다. 즉, 첫 번째 행은 첫 번째 열로, 두 번째 행은 두 번째 열로 옮기는 것입니다.

전치된 행렬은 다음과 같습니다:

$$
A^T = \begin{bmatrix} 2 & 0 \\ 1 & 0 \\ 4 & 3 \end{bmatrix}
$$

따라서 주어진 예제에서 행렬 $A$의 전치는 주어진 예와 같습니다:

$$
\begin{bmatrix} 2 & 1 & 4 \\ 0 & 0 & 3 \end{bmatrix}^T = \begin{bmatrix} 2 & 0 \\ 1 & 0 \\ 4 & 3 \end{bmatrix}
$$


이때 행렬의 전치를 벡터의 전치로 확장해보면, $a_i$가 $i$번째 원소인 $\mathbb{R}^n$ 벡터 $a$는 $n \times 1$ 행렬로 생각할 수 있으므로 $a^T$는 $[a_1, a_2, ..., a_n]$과 같이 $1 \times n$ 행렬로 정의할 수 있습니다. 이 개념을 $m \times n$ 행렬 $A$와 $\mathbb{R}^n$ 벡터 $v$의 곱에 행렬 $A$가 $1 \times n$ 행렬 $A = a^T$인 경우에 적용해보면. 그러면 $Av = a^Tv$인데 곱은 $1 \times 1$ 행렬, 즉 실수이므로 행렬 표시를 하지 않고 간단히 실수로 나타낼 수 있습니다.


$$a^T v = \sum_{i=1}^{n} a_i v_i$$


이를 $\mathbb{R}^n$ 벡터 $a$와 $v$의 표준 내적(inner product)이라고 부르는데, 나중에 벡터 공간에서 내적을 도입할 때 자세하게 공부하게 됩니다. 벡터 간의 내적을 도입하면 여러 행을 가진 행렬과 벡터가 곱해진 벡터는 각각의 행과 벡터의 곱을 내적으로 생각할 수 있습니다.


행렬의 transpose를 알고 나면 transpose에 의해 변하지 않는 행렬은 어떤 성질을 가지고 있을까 생각이 드는데 이를 대칭행렬이라고한다. 

대칭행렬의 간단한 성질 몇가지는 다음과 같다.

1. 대칭행렬은 정방행렬(square matrix)이다.
2. 대각행렬(diagonal matrix)은 모두 대칭행렬이다.
3. 임의의 행렬 $A$에 대해서, $A^T A$와 $AA^T$는 모두 대칭행렬이다.
4. $D$가 대각행렬이고 $A$가 임의의 행렬일 때, $ADA^T$와 $A^TDA$는 모두 대칭행렬이다.


In [ ]:
import numpy as np

# Example 1: Square matrix
A = np.array([[1, 2, 3],
              [2, 4, 5],
              [3, 5, 6]])

print("Example 1:")
print("Square matrix A:")
print(A)
print("Is A symmetric?", np.array_equal(A, A.T))

# Example 2: Diagonal matrix
D = np.diag([1, 2, 3])

print("\nExample 2:")
print("Diagonal matrix D:")
print(D)
print("Is D symmetric?", np.array_equal(D, D.T))

# Example 3: A^T A and AA^T
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])

print("\nExample 3:")
print("Matrix A:")
print(A)
ATA = np.dot(A.T, A)
AAT = np.dot(A, A.T)
print("A^T A:")
print(ATA)
print("Is A^T A symmetric?", np.array_equal(ATA, ATA.T))
print("AA^T:")
print(AAT)
print("Is AA^T symmetric?", np.array_equal(AAT, AAT.T))

# Example 4: ADA^T and A^TDA
D = np.diag([1, 2])
A = np.array([[1, 2],
              [3, 4]])

print("\nExample 4:")
print("Diagonal matrix D:")
print(D)
print("Matrix A:")
print(A)
ADA_T = np.dot(np.dot(A, D), A.T)
A_TDA = np.dot(np.dot(A.T, D), A)

print("ADA^T:")
print(ADA_T)
print("Is ADA^T symmetric?", np.array_equal(ADA_T, ADA_T.T))

print("A^TDA:")
print(A_TDA)
print("Is A^TDA symmetric?", np.array_equal(A_TDA, A_TDA.T))


주어진 연립일차방정식은 다음과 같습니다:

$$
\begin{cases}
x + y = 5 \\
2x - y = 1
\end{cases}
$$

이를 해결하기 위해 먼저 첫 번째 방정식을 사용하여 $ x $를 구합니다. 첫 번째 방정식에서 $ y $를 $ 5 - x $로 대체하면 다음과 같은 방정식이 됩니다:

$$
2x - (5 - x) = 1
$$

이를 풀어 $ x $를 구합니다:

$$
2x - 5 + x = 1 \\
3x - 5 = 1 \\
3x = 6 \\
x = \frac{6}{3} \\
x = 2
$$

이제 $ x $의 값을 알았으므로, 두 번째 방정식을 사용하여 $ y $를 구합니다. 두 번째 방정식에서 $ x $에 2를 대입하면 다음과 같은 방정식이 됩니다:

$$
2 \times 2 - y = 1 \\
4 - y = 1 \\
-y = 1 - 4 \\
-y = -3 \\
y = 3
$$

따라서 연립일차방정식의 해는 $ x = 2 $이고 $ y = 3 $입니다.


변수가 2개인 연립방정식은 2차원 평면에서 그래프로 나타낼 수 있습니다. 두 가지 관점이 있습니다:

* **row wise**: 각 방정식의 그래프를 그려서 그래프가 만나는 점이 두 방정식을 모두 만족하는 해로 이해하는 것입니다. 아래의 그림에서 파란색 직선은 첫 번째 선형 방정식을, 주황색 직선은 두 번째 선형 방정식을 나타냅니다. 두 직선이 만나는 점은 두 방정식의 해가 됩니다.


위의 그림에서 파란색 직선은 다음과 같은 첫 번째 선형 방정식을 나타냅니다:

$$
x + y = 3
$$

주황색 직선은 다음과 같은 두 번째 선형 방정식을 나타냅니다:

$$
2x - y = 1
$$

따라서 두 방정식을 모두 만족하는 해는 두 직선이 만나는 점입니다.


In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# 첫 번째 선형 방정식: x + y = 3
# 두 번째 선형 방정식: 2x - y = 1

# x 값 범위 설정
x = np.linspace(-2, 4, 100)

# 첫 번째 선형 방정식 그래프
y1 = 3 - x

# 두 번째 선형 방정식 그래프
y2 = 2*x - 1

# 그래프 그리기
plt.figure(figsize=(8, 6))
plt.plot(x, y1, '-b', label='x + y = 3')
plt.plot(x, y2, '-r', label='2x - y = 1')
plt.title('Linear Equations in 2D')
plt.xlabel('x')
plt.ylabel('y')
plt.grid(True)
plt.axhline(0, color='black',linewidth=0.5)
plt.axvline(0, color='black',linewidth=0.5)
plt.legend(loc='best')
plt.show()

# 2.3 An Example of Gaussian Elimination
다음과 같은 3개의 미지수에 대한 3개의 선형방정식으로 이루어진 연립방정식을 생각해보면

$$
\begin{cases}
2u + v + w = 5 \\
4u - 6v = -2 \\
-2u + 7v + 2w = 9
\end{cases}
$$

이를 행렬 형태로 나타내면 다음과 같습니다:

$$
\begin{bmatrix}
2 & 1 & 1 \\
4 & -6 & 0 \\
-2 & 7 & 2
\end{bmatrix}
\begin{bmatrix}
u \\
v \\
w
\end{bmatrix}
=
\begin{bmatrix}
5 \\
-2 \\
9
\end{bmatrix}
$$

가우스 소거법을 사용하여 행렬을 삼각행렬로 변환합니다. 첫 번째 열을 기준으로 다음과 같은 연산을 수행합니다:

1. 두 번째 행에서 첫 번째 행의 2배를 빼고, 세 번째 행에서 첫 번째 행의 -1배를 합니다.

$$
\begin{bmatrix}
2 & 1 & 1 \\
0 & -8 & -2 \\
0 & 8 & 3
\end{bmatrix}
\begin{bmatrix}
u \\
v \\
w
\end{bmatrix}
=
\begin{bmatrix}
5 \\
-12 \\
7
\end{bmatrix}
$$

2. 두 번째 행을 -1/8로 나누고, 세 번째 행을 1/8로 나눕니다.

$$
\begin{bmatrix}
2 & 1 & 1 \\
0 & 1 & 1/4 \\
0 & 1 & 3/8
\end{bmatrix}
\begin{bmatrix}
u \\
v \\
w
\end{bmatrix}
=
\begin{bmatrix}
5 \\
-12 \\
7
\end{bmatrix}
$$

3. 두 번째 행에서 세 번째 행을 빼서 두 번째 열의 세 번째 행을 0으로 만듭니다.

$$
\begin{bmatrix}
2 & 1 & 1 \\
0 & 1 & 1/4 \\
0 & 0 & 5/8
\end{bmatrix}
\begin{bmatrix}
u \\
v \\
w
\end{bmatrix}
=
\begin{bmatrix}
5 \\
-12 \\
-17/4
\end{bmatrix}
$$

4. 세 번째 행을 5/8로 나눕니다.

$$
\begin{bmatrix}
2 & 1 & 1 \\
0 & 1 & 1/4 \\
0 & 0 & 1
\end{bmatrix}
\begin{bmatrix}
u \\
v \\
w
\end{bmatrix}
=
\begin{bmatrix}
5 \\
-12 \\
-17/4
\end{bmatrix}
$$

따라서, 연립방정식의 해는 $ u = 2 $, $ v = -3 $, $ w = -17/4 $ 입니다.

In [ ]:
import numpy as np

# 연립방정식의 계수 행렬과 상수 벡터 정의
A = np.array([[2, 1, 1],
              [4, -6, 0],
              [-2, 7, 2]])

b = np.array([5, -2, 9])

# 초기 행렬과 벡터 출력
print("초기 행렬 A:\n", A)
print("초기 상수 벡터 b:", b)

# 가우스 소거법 적용
n = len(b)
for pivot_row in range(n):
    # 피봇 행의 요소를 1로 만들기 위해 나누기
    A[pivot_row] = A[pivot_row] / A[pivot_row, pivot_row]
    b[pivot_row] = b[pivot_row] / A[pivot_row, pivot_row]

    # 피봇 행을 이용하여 다른 행의 요소를 0으로 만들기
    for row in range(n):
        if row != pivot_row:
            multiplier = A[row, pivot_row]
            A[row] -= multiplier * A[pivot_row]
            b[row] -= multiplier * b[pivot_row]

    # 각 단계에서의 행렬과 벡터 출력
    print("\n피봇 행에 대한 가우스 소거법 적용 결과:")
    print("A:\n", A)
    print("b:", b)

# 결과 출력
print("\n연립방정식의 해:")
for i in range(n):
    print(f"x_{i+1} = {b[i]}")


이러한 과정을 Gaussian elimination(가우스 소거법)이라고 부릅니다. 이 과정을 거치면 i 번째 방정식에는 1,...,i-1번째 변수가 모두 소거되어 있고 변경된 계수 행렬을 $ C = (c_{ij}) $ 라 하면, 계수 행렬 관점에서는 $ c_{i1} = ... = c_{i(i-1)} = 0 $ 입니다. 어떤 행렬이 대각원소 아래쪽 원소들이 모두 0이면, 즉 $ A = (a_{ij}) $에서 $ a_{ij} = 0 $ if $ i > j $ 인 경우 이런 행렬들을 상삼각행렬(upper triangular matrix)이라고 하며, 반대의 경우 하삼각행렬(lower triangular matrix)이라고 부릅니다.


주어진 상삼각 행렬:

$$
\begin{bmatrix}
2 & 1 & 1 \\
0 & -8 & -2 \\
0 & 0 & 5/8
\end{bmatrix}
\begin{bmatrix}
u \\
v \\
w
\end{bmatrix}
=
\begin{bmatrix}
5 \\
-12 \\
-17/4
\end{bmatrix}
$$

1. 마지막 행부터 역순으로 계산합니다:
   - 세 번째 방정식: $ \frac{5}{8}w = -\frac{17}{4} \implies w = -\frac{17}{4} \times \frac{8}{5} = -2 $
   
2. 두 번째 방정식에 w의 값을 대입하여 계산합니다:
   - 두 번째 방정식: $ -8v - 2 \times (-2) = -12 \implies -8v + 4 = -12 \implies -8v = -16 \implies v = 2 $
   
3. 첫 번째 방정식에 v와 w의 값을 대입하여 계산합니다:
   - 첫 번째 방정식: $ 2u + 1 \times 2 + 1 \times (-2) = 5 \implies 2u + 2 - 2 = 5 \implies 2u = 5 \implies u = \frac{5}{2} $

따라서, 연립방정식의 해는 다음과 같습니다:
$$
u = \frac{5}{2}, \quad v = 2, \quad w = -2
$$


연립방정식에 따라서는 이러한 절차가 적용되는 과정에서 다음과 같은 두가지 이유로 중단될 수 있다.

* non-singular(curable by row exchange) : 두번째 행에 대한 소거과정에서 너무 많은 변수가 소거되면 세번째 행의 변수 소거가 진행되지 않을 수 있다. 이러한 경우 gaussian elimination 전에 두번째 행과 세번째 행을 교환한 후에 gaussian elimination을 수행하면 된다. 연립방정식에서 방정식의 나열 순서는 문제가 되지 않는것과 같은 원리이다.

* singular : 어느 두 행이 서로 상수배 관계가 있으면 소거과정에서 한 행이 모두 0으로 채워진다. 이 경우도 gaussian elimination을 통해 계수행렬을 상삼각행렬로 변경할 수 있는데 방정식의 우변에 따라서 back substitution이 적용 될 수도 있고 적용되지 않을 수도 있다. 

In [ ]:
import numpy as np

# 연립방정식의 계수 행렬과 상수 벡터 정의
A = np.array([[2, 1, 1],
              [0, -6, 4],  # 두 번째 행과 세 번째 행을 교환
              [4, 3, 2]])

b = np.array([5, -2, 9])

# 가우스 소거법 적용
n = len(b)
for pivot_row in range(n):
    # 피봇 행의 요소를 1로 만들기 위해 나누기
    A[pivot_row] = A[pivot_row] / A[pivot_row, pivot_row]
    b[pivot_row] = b[pivot_row] / A[pivot_row, pivot_row]

    # 피봇 행을 이용하여 다른 행의 요소를 0으로 만들기
    for row in range(n):
        if row != pivot_row:
            multiplier = A[row, pivot_row]
            A[row] -= multiplier * A[pivot_row]
            b[row] -= multiplier * b[pivot_row]

# 결과 출력
print("연립방정식의 해:")
for i in range(n):
    print(f"x_{i+1} = {b[i]}")


In [ ]:
import numpy as np

# 연립방정식의 계수 행렬과 상수 벡터 정의
A = np.array([[2, 1, 1],
              [4, 2, 2],  # 두 번째 행과 세 번째 행이 상수배 관계에 있음
              [1, 3, 2]])

b = np.array([5, 10, 9])

# 가우스 소거법 적용
n = len(b)
for pivot_row in range(n):
    # 피봇 행의 요소를 1로 만들기 위해 나누기
    A[pivot_row] = A[pivot_row] / A[pivot_row, pivot_row]
    b[pivot_row] = b[pivot_row] / A[pivot_row, pivot_row]

    # 피봇 행을 이용하여 다른 행의 요소를 0으로 만들기
    for row in range(n):
        if row != pivot_row:
            multiplier = A[row, pivot_row]
            A[row] -= multiplier * A[pivot_row]
            b[row] -= multiplier * b[pivot_row]

# 결과 출력
print("연립방정식의 해:")
for i in range(n):
    print(f"x_{i+1} = {b[i]}")

# 2.4 Block Matrices

R^n1벡터 u1, v1과 R^n2벡터 u2,v2에 대해서 



$$
u = \begin{bmatrix} u_1 \\ u_2 \end{bmatrix}, \quad v = \begin{bmatrix} v_1 \\ v_2 \end{bmatrix}
$$

위와 같이 주어진 두 벡터의 내적은 다음과 같이 계산됩니다:

$$
u^T v = \begin{bmatrix} u_1 & u_2 \end{bmatrix} \begin{bmatrix} v_1 \\ v_2 \end{bmatrix}
$$

또한, 행렬과 벡터의 곱은 내적의 반복이므로, $ m \times n_1 $ 행렬 $ A_{11} $과 $ m \times n_2 $ 행렬 $ A_{12} $로 구성된 행렬 $ A = [A_{11}, A_{12}] $와 벡터 $ v $의 곱은 $ A $의 각 행이 $ n_1 $과 $ n_2 $개의 원소를 가진 subvector가 합쳐진 것으로 생각할 수 있습니다. 따라서 위에서와 같은 곱을 $ m $번 반복하여 곱의 결과인 $ \mathbb{R}^m $ 벡터의 $ m $개의 원소를 계산할 수 있습니다.

즉, 

$$
Av = \begin{bmatrix} A_{11} \\ A_{21} \end{bmatrix} \begin{bmatrix} B_{11} & B_{21} \end{bmatrix} = A_{11}B_{11} + A_{12}B_{21}
$$

이 됨을 알 수 있습니다. 가장 우측의 행렬 덧셈은 $ A_{11}B_{11} $과 $ A_{12}B_{21} $가 모두 $ m \times l $ 행렬이어서 잘 정의됩니다. 그리고 $ A $와 $ B $의 역할이 바뀐 다음과 같은 형태의 행렬에도

$$
\begin{bmatrix} A_{11} \\ A_{21} \end{bmatrix} \begin{bmatrix} B_{11} & B_{21} \end{bmatrix} = \begin{bmatrix} A_{11}B_{11} & A_{11}B_{12} \\ A_{21}B_{11} & A_{21}B_{12} \end{bmatrix}
$$

이 성립하는 것을 확인할 수 있습니다.


더 많은 submatrix로 구성된 blockmatrix간의 곱은 여기에 기술된 두 가지 곱 표현을 반복적으로 적용하면 계산할 수 있습니다. 행렬 $A$가 작은 크기의 행렬 $A_{ij}$들에 대해 다음과 같이 block matrix로 표현된다고 하자:

$$
A = \begin{bmatrix} A_{11} & A_{12} \\ A_{21} & A_{22} \end{bmatrix}
$$

$A$를 구성하는 block들인 부분행렬들의 크기는 자연수 $m_i$, $n_i$에 대해서 $A_{11}: m_1 \times n_1$, $A_{12}: m_1 \times n_2$, $A_{21}: m_2 \times n_1$, $A_{22}: m_2 \times n_2$라 하면 $A: (m_1+m_2) \times (n_1+n_2)$가 됩니다. 또다른 행렬 $B$도 적절한 크기 $B_{ij}$들에 대해 block matrix로 $B = \begin{bmatrix} B_{11} & B_{12} \\ B_{21} & B_{22} \end{bmatrix}$ 로 표현되었다면,

$$
AB = \begin{bmatrix} A_{11} & A_{12} \\ A_{21} & A_{22} \end{bmatrix} \begin{bmatrix} B_{11} & B_{12} \\ B_{21} & B_{22} \end{bmatrix} = \begin{bmatrix} A_{11}B_{11} + A_{12}B_{21} & A_{11}B_{12} + A_{12}B_{22} \\ A_{21}B_{11} + A_{22}B_{21} & A_{21}B_{12} + A_{22}B_{22} \end{bmatrix}
$$

로 표현됨을 보일수 있습니다. 이런 행렬곱이 성립하는 조건은 block matrix곱에서 나타나는 $a_{ij}b_{jk}$들이 잘 정의될 조건인 $A_{ij}$의 열 개수와 $B_{jk}$의 행 개수가 일치하는 것이다.


In [ ]:
import numpy as np

# Define submatrices A11, A12, A21, A22
A11 = np.array([[1, 2],
                [3, 4]])
A12 = np.array([[5, 6],
                [7, 8]])
A21 = np.array([[9, 10],
                [11, 12]])
A22 = np.array([[13, 14],
                [15, 16]])

# Define submatrices B11, B12, B21, B22
B11 = np.array([[17, 18],
                [19, 20]])
B12 = np.array([[21, 22],
                [23, 24]])
B21 = np.array([[25, 26],
                [27, 28]])
B22 = np.array([[29, 30],
                [31, 32]])

# Combine submatrices to form matrices A and B
A = np.block([[A11, A12], [A21, A22]])
B = np.block([[B11, B12], [B21, B22]])

# Perform block matrix multiplication
result = np.zeros((4, 4))
result[:2, :2] = np.dot(A11, B11) + np.dot(A12, B21)
result[:2, 2:] = np.dot(A11, B12) + np.dot(A12, B22)
result[2:, :2] = np.dot(A21, B11) + np.dot(A22, B21)
result[2:, 2:] = np.dot(A21, B12) + np.dot(A22, B22)

# Print matrices A, B, and the result
print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nResult of block matrix multiplication:")
print(result)


Block matrix 간의 곱셈에서는 곱행렬의 각 블록을 구성하는 부분행렬의 순서를 정확하게 지켜야 합니다. 따라서 두 block matrix의 곱셈에서는 각 부분행렬의 순서가 일치해야 합니다. 그렇지 않으면 곱셈 결과가 달라질 수 있습니다.

예를 들어, $ A_{11}B_{11} + A_{12}B_{21} $이 $ B_{11}A_{11} + A_{12}B_{21} $이나 $ A_{11}B_{11} + B_{21}A_{12} $와 다를 수 있습니다. 이는 순서가 바뀜에 따라 부분행렬의 곱셈이 변경되기 때문입니다. 따라서 block matrix 곱셈에서는 부분행렬의 순서를 정확히 지켜주어야 합니다.


In [ ]:
import numpy as np

# Define submatrices A11, A12, B11, B21
A11 = np.array([[1, 2],
                [3, 4]])
A12 = np.array([[5, 6],
                [7, 8]])
B11 = np.array([[9, 10],
                [11, 12]])
B21 = np.array([[13, 14],
                [15, 16]])

# Calculate A11B11 + A12B21
result1 = np.dot(A11, B11) + np.dot(A12, B21)

# Calculate A11B11 + B21A12
result2 = np.dot(A11, B11) + np.dot(B21, A12)

# Print the results
print("Result of A11B11 + A12B21:")
print(result1)
print("\nResult of A11B11 + B21A12:")
print(result2)


# 2.5 Inverse of a Matrix
행렬간의 덧셈에 대해서는 항등원이 영행렬이고 자연스럽게 행렬의 모든 원소에 minus를 취한 행렬이 역원이다. 그리고 행렬 간의 곱셈에 대해서는 항등원으로 identity matrix가 정의되는 것을 공부했는데 이번에는 곱셈에 대한 역원의 역할을 하는 행렬을 찾아보자

곱셈에 대한 역원의 정의는 다음과 같다.
행렬 $A$가 $m \times n$ 행렬이고, 행렬 $B$가 $A$의 좌 역원(left-inverse)인 경우 $BA = I_n$이고, 행렬 $C$가 $A$의 우 역원(right-inverse)인 경우 $AC = I_m$입니다. 만약 행렬 $B$가 $A$의 좌 역원과 우 역원 모두인 경우, 즉 $BA = I_n$와 $AC = I_m$이 모두 성립하는 경우에는 $A$가 가역적(invertible)이라고 하며, $A$는 역행렬을 갖는다고 합니다.


In [ ]:
import numpy as np

def determinant(matrix):
    """행렬의 determinant를 계산하는 함수"""
    return np.linalg.det(matrix)

def cofactor(matrix, row, col):
    """주어진 행렬에서 주어진 행과 열을 제외한 부분행렬의 determinant를 계산하는 함수"""
    sub_matrix = np.delete(np.delete(matrix, row, axis=0), col, axis=1)
    return (-1) ** (row + col) * determinant(sub_matrix)

def adjugate(matrix):
    """행렬의 여인자 행렬을 계산하는 함수"""
    adj = np.zeros_like(matrix)
    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            adj[i, j] = cofactor(matrix, i, j)
    return adj.T

def inverse(matrix):
    """행렬의 역행렬을 계산하는 함수"""
    det = determinant(matrix)
    if det == 0:
        raise ValueError("행렬의 determinant가 0입니다.")
    adj = adjugate(matrix)
    return adj / det

# 예시 행렬 A
A = np.array([[1, 2], [3, 4]])

# 역행렬 계산
A_inv = inverse(A)

print("A의 역행렬:")
print(A_inv)


만약 행렬 $B$가 $k \times l$ 행렬이라면, $AB$와 $BA$가 잘 정의되기 위해서는 다음과 같은 조건이 필요합니다: $B$는 $n \times m$ 행렬이어야 합니다. 즉, $n = k$ 그리고 $l = m$이어야 합니다. 사실, $B$가 $A$의 역행렬이라면 $m = n$이 되며, 이는 나중에 설명하겠습니다.

만약 역행렬이 존재한다면 역행렬은 유일합니다. 즉, $B$와 $C$가 모두 $A$의 역행렬인 경우, 다음과 같은 관계가 성립합니다:

$$
\begin{align*}
B & = B \cdot I_m \\
& = B \cdot (A \cdot C) \\
& = (B \cdot A) \cdot C \\
& = I_n \cdot C \\
& = C
\end{align*}
$$

따라서 역행렬이 존재한다면 그 역행렬은 유일합니다.


행렬 $A$의 좌 역행렬(left-inverse) $B$를 사용하여 $Ax = b$를 해결할 때 주의해야 합니다. $A$의 좌 역행렬 $B$가 존재한다고 가정해 봅시다. 그렇다면 $Ax = b$에 좌변과 우변에 $b$를 곱하는 것으로 시작하여 $B(Ax) = Bb$가 되고, 따라서 $x = I_n x = (BA)x = B(Ax) = Bb$입니다. 그러나 $x = Bb$로 설정된 경우, $Ax = A(Bb) = (AB)b$가 $b$로 축소되지 않을 수 있습니다. 이는 $B$가 $A$의 우 역행렬(right-inverse)이 아닌 경우입니다. $A$가 역행렬 $B$를 가지고 있는 경우에만 $Bb$가 $Ax = b$의 해가 됩니다.


In [ ]:
import numpy as np

# 원래 행렬 A
A = np.array([[1, 2], [3, 4]])

# A의 determinant 계산
det_A = np.linalg.det(A)
print("Determinant of A:")
print(det_A)

# A의 determinant가 0이 아닌지 확인하여 역행렬이 존재하는지 검사
if det_A != 0:
    # 역행렬 계산
    A_inv = np.linalg.inv(A)
    print("\nInverse of A:")
    print(A_inv)
else:
    print("\nInverse of A does not exist.")

# 역행렬과 원래 행렬의 곱이 단위 행렬이 되는지 확인
if np.allclose(np.dot(A, A_inv), np.eye(A.shape[0])):
    print("\nA * A_inv equals the identity matrix.")
else:
    print("\nA * A_inv does not equal the identity matrix.")


Assume $A$ is an upper triangular matrix. Then $A$ is invertible if and only if every diagonal element of $A$ is non-zero. $A^{-1}$ is also upper triangular if it exists.


In [ ]:
import numpy as np

# 임의의 (n-1) x (n-1) 상삼각 행렬 생성
def random_upper_triangular(n):
    A = np.random.rand(n-1, n-1)
    upper_triangular = np.triu(A)
    return upper_triangular

# 임의의 n x 1 벡터 생성
def random_vector(n):
    v = np.random.rand(n, 1)
    return v

# 결합된 행렬의 역행렬 계산
def compute_inverse_of_combined_matrix(A, v):
    n = len(v) + 1
    combined_matrix = np.zeros((n, n))
    combined_matrix[:n-1, :n-1] = A
    combined_matrix[:n-1, n-1:] = v
    combined_matrix[n-1, n-1] = 1

    if np.all(np.diagonal(combined_matrix) != 0):
        try:
            inverse_matrix = np.linalg.inv(combined_matrix)
            print("결합된 행렬:\n", combined_matrix)
            print("결합된 행렬의 역행렬:\n", inverse_matrix)
        except np.linalg.LinAlgError:
            print("역행렬이 존재하지 않습니다.")
    else:
        print("대각원소 중에 0이 존재하여 역행렬을 계산할 수 없습니다.")

# 행렬 크기 정의
n = 8

# 임의의 (n-1) x (n-1) 상삼각 행렬 생성
A = random_upper_triangular(n)

# 임의의 n x 1 벡터 생성
v = random_vector(n-1)

# 결합된 행렬의 가역성 확인 및 역행렬 계산
compute_inverse_of_combined_matrix(A, v)


# 2.5.1 Triangular Factors
일반적으로 여러 하삼각 행렬들을 곱하더라도 그 곱은 하삼각행렬이다.다음과 같이 하삼각행렬을 만드는 세번의 과정을 살펴보면

[2 1 1 5]  l1 [2 1 1 5]    l2 [2 1 1 5]     l3 [2 1 1 5]
[4 -6 0 -2] =>[0 -8 -2 -12] =>[0 -8 -2 -12] => [0 -8 -2 -12]
[-2 7 2 9]    [-2 7 2 9]      [0 8 3 14]       [0 0 1 2]

여기에 사용된 세 하삼각행렬과 그 역행렬은 다음과 같다

L1 = [1 0 0]  L1=L1^-1 = [1 0 0]
     [-2 1 0]            [0 -8 -2 12]
     [0 0 1]             [0 0 1 2]

L2 = [1 0 0] L2 =L2^-1 = [1 0 0]
     [0 1 0]             [0 1 0]
     [1 0 1]             [-1 0 1]

L3 = [1 0 0] L3 = L3^-1 = [1 0 0]
     [0 1 0]              [2 1 0]
     [0 1 1]              [0 -1 1]

# 2.5.1 Triangular Factors

일반적으로 여러 하삼각 행렬들을 곱하더라도 그 곱은 하삼각행렬이다.다음과 같이 하삼각행렬을 만드는 세번의 과정을 살펴보면

$
\begin{bmatrix} 
2 & 1 & 1 & 5 \\
4 & -6 & 0 & -2 \\
-2 & 7 & 2 & 9
\end{bmatrix}
\quad \overset{L_1}{\rightarrow} \quad
\begin{bmatrix} 
2 & 1 & 1 & 5 \\
0 & -8 & -2 & -12 \\
0 & 8 & 3 & 14
\end{bmatrix}
\quad \overset{L_2}{\rightarrow} \quad
\begin{bmatrix} 
2 & 1 & 1 & 5 \\
0 & -8 & -2 & -12 \\
0 & 0 & 1 & 2
\end{bmatrix}
\quad \overset{L_3}{\rightarrow} \quad
\begin{bmatrix} 
2 & 1 & 1 & 5 \\
0 & -8 & -2 & -12 \\
0 & 0 & 1 & 2
\end{bmatrix}
$

여기에 사용된 세 하삼각행렬과 그 역행렬은 다음과 같다:

### \( L_1 \):
$
L_1 = 
\begin{bmatrix} 
1 & 0 & 0 \\
-2 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix}
\quad \text{and} \quad
L_1^{-1} = 
\begin{bmatrix} 
1 & 0 & 0 \\
0 & -8 & -2 \\
0 & 0 & 1
\end{bmatrix}
$

### \( L_2 \):
$
L_2 = 
\begin{bmatrix} 
1 & 0 & 0 \\
0 & 1 & 0 \\
1 & 0 & 1
\end{bmatrix}
\quad \text{and} \quad
L_2^{-1} = 
\begin{bmatrix} 
1 & 0 & 0 \\
0 & 1 & 0 \\
-1 & 0 & 1
\end{bmatrix}
$

### \( L_3 \):
$
L_3 = 
\begin{bmatrix} 
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 1 & 1
\end{bmatrix}
\quad \text{and} \quad
L_3^{-1} = 
\begin{bmatrix} 
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & -1 & 1
\end{bmatrix}
$


### $L$ 행렬 계산:
$
L = L_1 \times L_2 \times L_3
$

주어진 $L_1$, $L_2$, $L_3$ 행렬은 이미 주어져 있습니다:

$
L_1 = \begin{bmatrix} 
1 & 0 & 0 \\
-2 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix}
$

$
L_2 = \begin{bmatrix} 
1 & 0 & 0 \\
0 & 1 & 0 \\
1 & 0 & 1
\end{bmatrix}
$

$
L_3 = \begin{bmatrix} 
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 1 & 1
\end{bmatrix}
$

따라서, $L$ 행렬은 $L_1$, $L_2$, $L_3$의 곱입니다:

$
L = L_1 \times L_2 \times L_3
$

계산을 해보면:

$
L = \begin{bmatrix} 
1 & 0 & 0 \\
-2 & 1 & 0 \\
-2 & 1 & 1
\end{bmatrix}
$


### $D$ 행렬 계산:
$
D = L_3^{-1} \times L_2^{-1} \times L_1^{-1} \times A
$

주어진 $L_1$, $L_2$, $L_3$ 행렬의 역행렬은 이미 주어져 있습니다:

$
L_1^{-1} = \begin{bmatrix} 
1 & 0 & 0 \\
0 & -8 & -2 \\
0 & 0 & 1
\end{bmatrix}
$

$
L_2^{-1} = \begin{bmatrix} 
1 & 0 & 0 \\
0 & 1 & 0 \\
-1 & 0 & 1
\end{bmatrix}
$

$
L_3^{-1} = \begin{bmatrix} 
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & -1 & 1
\end{bmatrix}
$

주어진 행렬 $A$는 다음과 같았습니다:

$
A = \begin{bmatrix} 
2 & 1 & 1 & 5 \\
4 & -6 & 0 & -2 \\
-2 & 7 & 2 & 9
\end{bmatrix}
$

따라서, $D$ 행렬은 다음과 같습니다:

$
D = L_3^{-1} \times L_2^{-1} \times L_1^{-1} \times A
$

계산을 해보면:

$
D = \begin{bmatrix} 
2 & 0 & 0 & 0 \\
0 & -8 & 0 & 0 \\
0 & 0 & 1 & 0 \\
0 & 0 & 0 & 1
\end{bmatrix}
$


### $U$ 행렬 계산:
$
U = A \times L_1 \times L_2 \times L_3
$

주어진 행렬 $A$는 다음과 같았습니다:

$
A = \begin{bmatrix} 
2 & 1 & 1 & 5 \\
4 & -6 & 0 & -2 \\
-2 & 7 & 2 & 9
\end{bmatrix}
$

따라서, $U$ 행렬은 다음과 같습니다:

$
U = A \times L_1 \times L_2 \times L_3
$

계산을 해보면:

$
U = \begin{bmatrix} 
2 & 1 & 1 & 5 \\
0 & -8 & -2 & -12 \\
0 & 0 & 1 & 2
\end{bmatrix}
$


세 하삼각행렬을 순서대로 곱하면 여러번의 Gaussian elimination을 표현하는 하삼각행렬을 얻을 수 있다. 일반적으로 여러 하삼각행렬을 곱하더라도 그 곱은 하삼각행렬이다. 

주어진 행렬 $A$의 $LDU$ 분해는 다음과 같습니다:

### $L$ 행렬:
$
L = \begin{bmatrix} 
1 & 0 & 0 \\
-2 & 1 & 0 \\
-2 & 1 & 1
\end{bmatrix}
$

### $D$ 행렬:
$
D = \begin{bmatrix} 
2 & 0 & 0 & 0 \\
0 & -8 & 0 & 0 \\
0 & 0 & 1 & 0 \\
0 & 0 & 0 & 1
\end{bmatrix}
$

### $U$ 행렬:
$
U = \begin{bmatrix} 
2 & 1 & 1 & 5 \\
0 & -8 & -2 & -12 \\
0 & 0 & 1 & 2
\end{bmatrix}
$

따라서, 주어진 행렬 $A$의 $LDU$ 분해는 다음과 같습니다:

$$
A = \begin{bmatrix} 
1 & 0 & 0 \\
-2 & 1 & 0 \\
-2 & 1 & 1
\end{bmatrix} \times 
\begin{bmatrix} 
2 & 0 & 0 & 0 \\
0 & -8 & 0 & 0 \\
0 & 0 & 1 & 0 \\
0 & 0 & 0 & 1
\end{bmatrix} \times 
\begin{bmatrix} 
2 & 1 & 1 & 5 \\
0 & -8 & -2 & -12 \\
0 & 0 & 1 & 2
\end{bmatrix}
$$


In [ ]:
import numpy as np

# 두 개의 임의의 하삼각 행렬을 생성하는 함수
def random_lower_triangular(n):
    A = np.random.rand(n, n)
    lower_triangular = np.tril(A)
    return lower_triangular

# 임의의 하삼각 행렬들을 곱한 결과가 하삼각 행렬인지 확인하는 함수
def check_lower_triangular_product(n):
    # 임의의 하삼각 행렬 생성
    matrices = [random_lower_triangular(n) for _ in range(3)]
    
    # 모든 행렬을 곱함
    result = matrices[0]
    for i in range(1, len(matrices)):
        result = np.dot(result, matrices[i])
    
    # 결과가 하삼각 행렬인지 확인
    is_lower_triangular = np.all(np.tril(result) == result)
    
    return is_lower_triangular

# n 값 정의
n = 4

# 함수 호출하여 결과 출력
is_lower_triangular_result = check_lower_triangular_product(n)
print(f"하삼각 행렬들을 곱한 결과는 하삼각 행렬입니다: {is_lower_triangular_result}")


In [ ]:
import numpy as np

# 주어진 행렬 A
A = np.array([
    [2, 1, 1, 5],
    [4, -6, 0, -2],
    [-2, 7, 2, 9]
])

# L1, L2, L3 행렬
L1 = np.array([
    [1, 0, 0],
    [-2, 1, 0],
    [0, 0, 1]
])

L2 = np.array([
    [1, 0, 0],
    [0, 1, 0],
    [1, 0, 1]
])

L3 = np.array([
    [1, 0, 0],
    [0, 1, 0],
    [0, 1, 1]
])

# L 행렬 계산
L = np.dot(L1, np.dot(L2, L3))
print("L 행렬:")
print(L)
print()

# L1, L2, L3의 역행렬 계산
L1_inv = np.linalg.inv(L1)
L2_inv = np.linalg.inv(L2)
L3_inv = np.linalg.inv(L3)

# D 행렬 계산
D = np.dot(np.dot(np.dot(L3_inv, L2_inv), L1_inv), A)
print("D 행렬:")
print(D)
print()

# U 행렬 계산
U = np.dot(np.dot(np.dot(A, L1), L2), L3)
print("U 행렬:")
print(U)
print()

# LDU 분해의 결과
print("주어진 행렬 A의 LDU 분해:")
print(np.dot(np.dot(L, D), U))


## 2.5.2 LU-Factorization

우리가 위에서 수행한 Gaussian elimination은 i번째 행을 변경할 때, i번째 행보다 위쪽 행들의 선형조합을 i번째 행에 더하는 방법으로 이루어졌다. 따라서 이를 나타내는 행렬이 하삼각행렬일 뿐만 아니라 대각원소가 반드시 1이 됨을 알 수 있다. 이 과정을 나타내는 대각원소가 1인 하삼각 행렬을 $L$로 나타내고 변경된 계수행렬을 상삼각행렬 $U$라 하면 $A = LU$로 분해되는데 이를 LU-Factorization이라고 부른다. LU-Factorization을 얻으면

$Ax = b \Rightarrow LUx = b$ 또는 $Ly = b$  
$\Rightarrow y = L^{-1}b$  
$\Rightarrow Ux = y = L^{-1} b$  
$\Rightarrow x = U^{-1}L^{-1} b$


를 통해서 선형연립방정식을 풀 수 있다. 이전에 언급한 바와 같이 계수행렬이 삼각행렬이면 back-substitution에 의해 방정식을 간단하게 풀 수 있따. 적절한 대각행렬 D를 이용하면 U도 대각원소가 1이 되도록 변경하여 A = LDU 분해가 가능해진다. 대각행렬 D의 원소가 모두 0이 아닌경우 이러한 분해가 유일한데, 한 행렬에서 두가지 분해 $L_1D_1U_1 = L_2D_2U_2$ 를 고려하자. 이등식에서 $L_2$와 $U_1$을 반대편으로 이항시키면 $L_2^{-1}L_1D_1 = D_2U_2U_1^{-1}$를 얻는다. 한번더 $D_1$을 오른쪽으로 이항시키면 $L_2^{-1}L_1 = D_2U_2U_1^{-1}D_1^{-1}$를 얻는다. $L_2^{-1}L_1$과 $U_2U_1^{-1}$은 각각 하삼각행렬과 상삼각행렬이고, $L_2^{-1}L_1$의 대각원소들이 모두 1임도 알수 있다. 또한 대각행렬 $D_2$와 $D_1^{-1}$을 곱하는 것은 상삼각행렬의 형태에 영향을 끼치지 못하므로 $L_2^{-1}L_1 = D_2U_2U_1^{-1}D_1^{-1}$ 의 좌변은 대각원소가 1인 하삼각행렬이고 우변은 상삼각행렬이다. 따라서 양변 모두 identity matrix여야 한다. $L_2^{-1}L_1 = I$ 로부터 $L_1 = L_2$를 얻게 되고 $D_1 = D_2$ $U_1 = U_2$를 차례로 얻을 수 있다.


In [ ]:
import numpy as np
import scipy.linalg

# 주어진 계수 행렬 A
A = np.array([
    [2, 1, 1],
    [4, -6, 0],
    [-2, 7, 2]
])

# LU 분해
P, L, U = scipy.linalg.lu(A)

# 상삼각 행렬 U와 하삼각 행렬 L을 출력
print("U 행렬:")
print(U)
print()

print("L 행렬:")
print(L)
print()

# 상삼각 행렬 U와 하삼각 행렬 L을 이용하여 b 계산
b = np.array([5, -2, 9])
y = np.linalg.solve(L, b)
x = np.linalg.solve(U, y)

print("x 값:")
print(x)


In [ ]:
import numpy as np

# 두 개의 LDU 분해
L1 = np.array([[1, 0, 0], [2, 1, 0], [3, 4, 1]])
D1 = np.array([[2, 0, 0], [0, 3, 0], [0, 0, 4]])
U1 = np.array([[1, 2, 3], [0, 1, 4], [0, 0, 1]])

L2 = np.array([[1, 0, 0], [4, 1, 0], [5, 6, 1]])
D2 = np.array([[5, 0, 0], [0, 6, 0], [0, 0, 7]])
U2 = np.array([[1, 4, 5], [0, 1, 6], [0, 0, 1]])

# 관계식 검증
result = np.allclose(np.dot(np.dot(L1, D1), U1), np.dot(np.dot(L2, D2), U2))
print("두 LDU 분해로 주어진 관계식 검증 결과:", result)

# 관계식의 좌변 계산
left_hand_side = np.dot(np.linalg.inv(L2), L1)

# 관계식의 우변 계산
right_hand_side = np.dot(np.dot(np.dot(D2, U2), np.linalg.inv(U1)), np.linalg.inv(D1))

# 관계식의 좌변과 우변이 동일한지 검증
result_l_eq_r = np.allclose(left_hand_side, right_hand_side)

# L1 = L2, D1 = D2 여부 출력
print("L1 = L2인가요?", np.allclose(L1, L2))
print("D1 = D2인가요?", np.allclose(D1, D2))


LU-Factorization with Row Exchange

Permutation matrix는 identity matrix의 두 열을 여러번 교환한 행렬로 생각할 수 있다. 여러번 교환했지만 permutation matrix의 각 행과 열들은 한 원소만 1을 값으로 갖고 나머지 원소들은 모두 0 이다. 다음과 같은 행렬

$$
A = \begin{bmatrix}
0 & 2 & 3 \\
4 & 5 & 6 \\
\end{bmatrix}
$$

에 대해서는 Gaussian Elimination을 시작할 수 없다. 하지만 두 방정식의 순서를 바꾸듯이 첫번째 행과 두번째 행을 교환하면 Gaussian elimination을 수행할 수 있다. 이 교환에 대응되는 permutation matrix는

$$
P = \begin{bmatrix}
0 & 1 \\
1 & 0 \\
\end{bmatrix}
$$

이고, 이렇게 행을 교환한 행렬

$$
PA = \begin{bmatrix}
0 & 1 \\
1 & 0 \\
\end{bmatrix}
\begin{bmatrix}
0 & 2 & 3 \\
4 & 5 & 6 \\
\end{bmatrix}
=
\begin{bmatrix}
4 & 5 & 6 \\
0 & 2 & 3 \\
\end{bmatrix}
$$

에 대해서는 앞 절 처럼 LU-Factorization을 수행하여 $PA = LU$를 만족하는 하삼각행렬 $L$ 과 상삼각 행렬 $U$를 얻을 수 있다.


In [ ]:
import numpy as np

# 주어진 행렬 A
A = np.array([[0, 2, 3], [4, 5, 6]])

# 순서를 바꾸어 행을 교환하는 permutation matrix P
P = np.array([[0, 1], [1, 0]])

# 행을 교환한 행렬 PA
PA = np.dot(P, A)

print("주어진 행렬 A:")
print(A)
print()

print("Permutation matrix P:")
print(P)
print()

print("행을 교환한 행렬 PA:")
print(PA)


**2.6 Inverse of Block Matrices**

A가 정사각행렬로서 작은 크기의 정사각행렬 A11과 A22에 대해 다음과 같이 block matrix로 표현된다고 하자:

$$
A = \begin{bmatrix} A_{11} & A_{12} \\ A_{21} & A_{22} \end{bmatrix}
$$

만약 $A_{11}$이 invertible하다면 Gaussian elimination에 의해 $A_{21}$을 소거할 수 있다. 이 소거 과정을 행렬을 이용하여 표현하면 다음과 같다.

$$
\begin{bmatrix} A_{11}^{-1} & 0 \\ -A_{21}A_{11}^{-1} & I_{22} \end{bmatrix}
\begin{bmatrix} A_{11} & A_{12} \\ A_{21} & A_{22} \end{bmatrix}
=
\begin{bmatrix} I_{11} & A_{11}^{-1}A_{12} \\ 0 & A_{22} - A_{21}A_{11}^{-1}A_{12} \end{bmatrix}
$$

마찬가지로 $A_{22}$가 invertible 하다면 $A_{12}$를 소거할 수 있다며 이 Gaussian elimination은

$$
\begin{bmatrix} I_{11} & -A_{12}A_{22}^{-1} \\ 0 & A_{22}^{-1} \end{bmatrix}
\begin{bmatrix} A_{11} & A_{12} \\ A_{21} & A_{22} \end{bmatrix}
=
\begin{bmatrix} A_{11} - A_{12}A_{22}^{-1}A_{21} & 0 \\ A_{22}^{-1}A_{21} & I_{22} \end{bmatrix}
$$

로 표현된다.


이 우변의 행렬을 간단히 나타내기 위해 
S22 = A22 - A21A11^-1A12
라는 행렬을 도입하자. 이 행렬 S22를 Schur complement of A11 with respect to A라고 부른다.  그러면 우변 행렬은 [I11 A11^-1A12]
                                                                                                         [0 S22]
로 나타낼 수 있다. 추가적으로 S22가 invertible하다면 다음과 같은 Gaussian elimination을 수행할 수 있다.

[I11 -A11^-1A12S22^-1][I11 A11^-1A12] = [I11 0]
[0   S22^-1]          [0 S22]           [0 I22]

행렬 A의 왼쪽에 곱해진 두 행렬을 곱하여 표현하면 

[I11 -A11^-1A12S22^-1][A11^-1 0]      [A11 A12] = [I11 0]
[0 S22^-1]            [-A21A11^-1 I22][A21 A22]   [0 I22]

을 얻게 되어 원하던 inverse는 왼쪽에 곱해진 두 행렬의 곱인
[A11 A12]^-1 = [I11 -A11^-1A12S22^-1][A11^-1]
[A21 A22]      [0 S22^-1]